on: [push, pull_request]

name: R-CMD-check

jobs:
  build: 
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build . --file Dockerfile
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
